name: Build
on: [push, pull_request]
jobs:
  build-js:
    name: build-js
    runs-on: ubuntu-latest

    steps:
    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install
      working-directory: parcel-client
      run: npm ci

    - name: Build
      working-directory: parcel-client
      run: npm run build
    
    - name: Test
      working-directory: parcel-client
      run: npm run test:ci
  
  build-dotnet:
    name: build-dotnet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .Net Core
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x
      
      - name: Install
        working-directory: parcel-server
        run: dotnet restore

      - name: Build
        working-directory: parcel-server
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: parcel-server
        run: dotnet test --no-restore --verbosity normal